<?php if($this->getSource() instanceof Mage_Sales_Model_Order): ?>

    <?php if ((float)$this->getSource()->getEasycreditAmountRefunded() > 0): ?>
        <tr>
            <td class="label"><strong><?php echo Mage::helper('fee')->__('Interest Refunded') ?></strong></td>
            <td><strong><?php echo $this->getSource()->getEasycreditAmountRefunded(); ?></strong></td>
        </tr>
    <?php endif; ?>

<?php else: ?>

    <?php if ((float)$this->getSource()->getEasycreditAmount()): ?>
        <tr>
            <td class="label"><strong><?php echo Mage::helper('fee')->__('Interest Refunded') ?></strong></td>
            <td><strong><?php echo $this->getSource()->getEasycreditAmount(); ?></strong></td>
        </tr>
    <?php endif;  ?>

<?php endif; ?>

