web:
  image: alexcheng/magento
  ports:
    - "8004:80"
  links:
    - mysql
    - redis
  env_file:
    - env
  volumes:
    - ./app/etc/modules/Netzkollektiv_EasyCredit.xml:/var/www/htdocs/app/etc/modules/Netzkollektiv_EasyCredit.xml
    - ./app/code/community/Netzkollektiv/EasyCredit:/var/www/htdocs/app/code/community/Netzkollektiv/EasyCredit
    - ./app/design/adminhtml/base/default/template/easycredit:/var/www/htdocs/app/design/adminhtml/base/default/template/easycredit
    - ./app/design/adminhtml/base/default/layout/easycredit.xml:/var/www/htdocs/app/design/adminhtml/base/default/layout/easycredit.xml
    - ./app/design/frontend/base/default/layout/easycredit.xml:/var/www/htdocs/app/design/frontend/base/default/layout/easycredit.xml
    - ./app/design/frontend/base/default/template/easycredit:/var/www/htdocs/app/design/frontend/base/default/template/easycredit
    - ./app/locale/de_DE/Netzkollektiv_EasyCredit.csv:/var/www/htdocs/app/locale/de_DE/Netzkollektiv_EasyCredit.csv
    
mysql:
  image: mysql:5.6.23
  env_file:
    - env

redis:
  image: redis
  ports:
    - 6379
