<?php
/**
 * @see Netzkollektiv_EasyCredit_Block_Adminhtml_System_Config_ApiWizard
 */
?>
<script>
    var getJSON = function(url, successHandler, errorHandler) {
        var xhr = typeof XMLHttpRequest != 'undefined'
            ? new XMLHttpRequest()
            : new ActiveXObject('Microsoft.XMLHTTP');
        xhr.open('get', url, true);
        xhr.onreadystatechange = function() {
            var status,
                data;

            if (xhr.readyState == 4) {
                status = xhr.status;
                if (status == 200) {
                    data = JSON.parse(xhr.responseText);
                    successHandler && successHandler(data);
                } else {
                    errorHandler && errorHandler(status);
                }
            }
        };
        xhr.send();
    };

    document.addEventListener("DOMContentLoaded", function(event) {
        document.getElementById('<?php echo $this->getHtmlId() ?>').onclick=function () {
            var baseUrl = '<?php echo $this->getButtonUrl()?>',
                apiKey = $('payment_easycredit_api_key').value,
                apiToken = $('payment_easycredit_api_token').value,
                apiSignature = $('payment_easycredit_api_signature').value,
                url = baseUrl + "?apiKey=" + encodeURIComponent(apiKey) + "&apiToken=" + encodeURIComponent(apiToken)+ "&apiSignature=" + encodeURIComponent(apiSignature);

            if (apiKey.length < 1 || apiToken.length < 1) {
                alert('<?php echo $this->escapeHtml($this->getInputIncompleteMessage()); ?>');
                return;
            }

            getJSON(url, function(data) {
                if (data.status) {
                    alert('<?php echo $this->escapeHtml($this->getSuccessMessage()); ?>');
                } else {
                    alert(Translator.translate(data.errorMessage));
                }
            }, function(status) {
                alert('<?php echo $this->escapeHtml($this->getErrorMessage()); ?>');
            });
        }
    });

</script>

<div class="pp-buttons-container">
    <button class="scalable" type="button" id="<?php echo $this->getHtmlId() ?>">
        <span><span><span><?php echo $this->escapeHtml($this->getButtonLabel()); ?></span></span></span>
    </button>
</div>
