<?php
/**
 * Checkout Form
 *
 * @see Netzkollektiv_EasyCredit_Block_Form
 */

$error = $this->checkAvailability();
?>
<fieldset class="form-list">
    <ul id="payment_form_<?php echo $this->getMethodCode(); ?>" style="display:none">
        <li>
            <input type="hidden" name="easycredit[submit]" id="easycredit-submit" class="required-entry absolute-advice" />
            <input type="hidden" name="easycredit[number-of-installments]" id="easycredit-number-of-installments" value="" />

            <script>
            if (typeof appylEasyCreditCheckoutBehavior === 'function') {
                appylEasyCreditCheckoutBehavior();
            }
            </script>
            <easycredit-checkout
                webshop-id="<?php echo $this->getWebshopId(); ?>"
                amount="<?php echo $this->getGrandTotal(); ?>"
                alert="<?php echo $error; ?>"
            ></easycredit-checkout>
        </li>
    </ul>
</fieldset>