<p>
    <easycredit-checkout-label>
        <?php echo $this->getMethod()->getTitle() ?>
    </easycredit-checkout-label>
    <easycredit-checkout payment-plan="<?php echo $this->escapeHtml($this->getPaymentPlan()); ?>">
        <p><strong>Transaktions-Nr:</strong> <?php echo $this->escapeHtml($this->getInfoAdditionalData('transaction_id')); ?></p>
    </easycredit-checkout>

    <?php if ($this->getInfoAdditionalData('is_captured')) : ?>
    <p><strong>Transaktions-Nr:</strong> <?php echo $this->escapeHtml($this->getInfoAdditionalData('transaction_id')); ?></p>
    <?php endif; ?>
</p>
