<?php 
$code = 'easycredit_amount';
if ($this->getSource() instanceof Mage_Sales_Model_Order) {
    $code = 'easycredit_amount_refunded';
}
?>

<?php if ((float)$this->getSource()->getData($code) > 0): ?>
    <tr>
        <td class="label"><strong><?php echo Mage::helper('easycredit')->__('Interest Refunded') ?></strong></td>
        <td><strong><?php echo Mage::helper('adminhtml/sales')->displayPriceAttribute($this->getSource(), $code); ?></strong></td>
    </tr>
<?php endif; ?>
