<?php
$t = $this->getTextConsent();
$textConsent = $t['text'];
$textConsentError = $t['error'];
?>


<fieldset class="form-list">
    <ul id="payment_form_<?php echo $this->getMethodCode(); ?>" style="display:none">
        <li>
            <div class="input-box">
                <?php if ($error = $this->checkAvailability() || $textConsentError) : ?>


                    <?php echo $error; ?>

                    <?php echo $textConsent; ?>

                    <script>
                        var radio = $('p_method_easycredit');
                        radio.disabled = true;
                        radio.checked = false;
                        radio.siblings('label')[0].down('img').addClassName('easycredit-disabled');
                        $('payment_form_easycredit').show();
                    </script>

                <?php else: ?>

                    <div id="easycredit-agreement-block">
                        <p>Datenübermittlung Ratenkauf by easyCredit</p>
                        <p>
                            <label for="easycredit-agreement">
                                <input type="checkbox" class="required-entry" id="easycredit-agreement"/>
                                <span id="easycredit-agreement-text"><?php echo $this->escapeHtml($textConsent); ?></span>
                            </label>
                        </p>
                    </div>
                <?php endif; ?>
            </div>
        </li>
    </ul>
</fieldset>
