<p>
    <strong><?php echo $this->getMethod()->getTitle() ?></strong><br />

    <?php echo $this->getInfoAdditionalData('redemption_plan'); ?><br />

    <?php if ($this->getInfoAdditionalData('is_captured')) : ?>
    <strong>Transaktions-Nr:</strong> <?php echo $this->getInfoAdditionalData('transaction_id'); ?><br />
    <?php else: ?>
    <a href="<?php echo $this->getInfoAdditionalData('pre_contract_information_url'); ?>" target="_blank">Vorvertragliche Informationen zum Ratenkauf hier abrufen</a>
    <?php endif; ?>
</p>
