<div class="easycredit-container">
    <img src="https://static.easycredit.de/content/image/logo/ratenkauf_42_55.png" height="35" />
    <span class="easycredit-description">

        <a href="https://www.easycredit.de/Ratenkauf.htm" onclick="javascript:window.open('https://www.easycredit.de/Ratenkauf.htm','whatiseasycredit','toolbar=no, location=no, directories=no, status=no, menubar=no, scrollbars=yes, resizable=yes, ,left=0, top=0, width=800, height=600'); return false;" class="easycredit-tooltip">Was ist Ratenkauf by easyCredit?</a>
    </span>
</div>
<style>
div.easycredit-container>img {
 width: 46px;
 height: 35px;
}
div.easycredit-description a {
}
span.easycredit-agreement {
 display:table;
}
span.easycredit-agreement>input, span.easycredit>label {
 display:table-cell;
}

a.easycredit-tooltip {
float: none !important;
line-height: 35px;
}
div.easycredit-tooltip {
 padding: 10px; 
}
img.easycredit-disabled {
 -webkit-filter:grayscale(100%); 
 filter:grayscale(100%);
}
div.easycredit-description {
 display: inline-block; 
 align-self: flex-end; 
}
div.easycredit-container {
 display:flex;
}
</style>
