<script src="https://ratenkauf.easycredit.de/ratenkauf/js/paymentPagePlugin.js" type="text/javascript"></script>
<script>
(function($) {

    var guid = function() {
      function s4() {
        return Math.floor((1 + Math.random()) * 0x10000)
          .toString(16)
          .substring(1);
      }
      return s4() + s4() + '-' + s4() + '-' + s4() + '-' +
        s4() + '-' + s4() + s4() + s4();
    };
    
    var getElementId = function() {
        return 'easycredit-pp-plugin-placeholder-'+guid();
    };

    /**
     *
     * @param {string} price
     * @returns {Number}
     */
    var getPriceAsFloat = function (price) {
        var separatorComa,
            separatorDot;

        price = price.replace(/[^\d.,-]/g,'');

        separatorComa = price.indexOf(',');
        separatorDot = price.indexOf('.');

        if (separatorComa > -1 && separatorDot > -1) {
            if (separatorComa > separatorDot) {
                price = price.replace(/\./g, '');
                price = price.replace(',', '.');
            } else {
                price = price.replace(/,/g, '');
            }
        }  else if (separatorComa > -1) {
            price = price.replace(',', '.');
        }

        return parseFloat(price);
    };

    $$('.price-box').each(function(element){
       var elementId = 'easycredit-pp-plugin-placeholder-'+guid();

       element.insert('<div id="'+elementId+'"></div>');

       rkPlugin.anzeige(elementId,{
            webshopId : '<?php echo Mage::getStoreConfig('payment/easycredit/api_key'); ?>',
            finanzierungsbetrag: function() {
                var priceElement = element.down('.price'); 
                if (typeof priceElement == 'undefined') {
                    return false;
                }
                return getPriceAsFloat(priceElement.innerHTML.stripTags());
            }(),
            textVariante: 'KURZ'
        });
    }); 
}());
</script>
